apiVersion: v1
kind: Namespace
metadata:
  name: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd2
  namespace: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
      instance: etcd2
  template:
    metadata:
      labels:
        app: etcd
        instance: etcd2
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.9
          command:
            - /usr/local/bin/etcd
          env:
            - name: ETCD_NAME
              value: "etcd2"
            - name: ETCD_DATA_DIR
              value: "/etcd-data"
            - name: ETCD_LISTEN_CLIENT_URLS
              value: "http://0.0.0.0:23791"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://192.168.1.111:23791"
            - name: ETCD_LISTEN_PEER_URLS
              value: "http://0.0.0.0:23801"
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: "http://192.168.1.111:23801"
            - name: ETCD_INITIAL_CLUSTER
              value: "etcd1=http://192.168.1.111:2380,etcd2=http://192.168.1.111:23801,etcd3=http://192.168.1.111:23802"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-1"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: "new"
          ports:
            - containerPort: 23791
              name: client
            - containerPort: 23801
              name: peer
          volumeMounts:
            - name: data
              mountPath: /etcd-data
      volumes:
        - name: data
          hostPath:
            path: /var/lib/etcd2
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  namespace: etcd
spec:
  selector:
    app: etcd
    instance: etcd2
  ports:
    - name: client
      port: 23791
      targetPort: 23791
      protocol: TCP
  type: ClusterIP
