apiVersion: apps/v1
kind: Deployment
metadata:
  name: conductor
  namespace: conductor
  labels:
    app: conductor
    mode: centralized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conductor
      mode: centralized
  template:
    metadata:
      labels:
        app: conductor
        mode: centralized
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: conductor
          image: esadakcam/private:conductor
          imagePullPolicy: Always
          args:
            - centralized
            - /config/config.yaml
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: kubeconfigs
              mountPath: /kubeconfigs
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: conductor-config
        - name: kubeconfigs
          secret:
            secretName: conductor-kubeconfigs
